DIMENSIONS = {
    "Purpose and Alignment": list(range(1, 6)),
    "Workflow Integration": list(range(6, 11)),
    "Skill and Judgment": list(range(11, 16)),
    "Risk and Responsible Use": list(range(16, 21)),
    "Impact and Measurement": list(range(21, 26)),
}

QUESTIONS = {
    1: "I can name the business or professional outcome I expect AI to improve.",
    2: "I use AI to address defined problems, not simply because the technology is available.",
    3: "I prioritize AI opportunities based on value, feasibility, and risk.",
    4: "I know which decisions and tasks should remain primarily human-led.",
    5: "My AI use supports explicit career, business, team, or performance goals.",
    6: "I use AI within documented or consistently repeated workflows.",
    7: "I know which workflow steps benefit from AI and which do not.",
    8: "I use reusable prompts, templates, instructions, or quality checks for recurring work.",
    9: "I can move efficiently from AI output to an approved, completed work product.",
    10: "AI reduces cycle time, rework, or manual effort rather than adding complexity.",
    11: "I provide sufficient context, constraints, examples, and success criteria.",
    12: "I can identify incomplete, misleading, unsupported, or incorrect output.",
    13: "I test and refine outputs rather than accepting the first response.",
    14: "I select tools based on the task, data, risk, and required capability.",
    15: "I apply professional judgment and accountability before using or sharing output.",
    16: "I do not enter confidential, sensitive, personal, or restricted information without authorization.",
    17: "I verify material factual claims using appropriate sources.",
    18: "I understand how the tools I use store, process, or expose data.",
    19: "I review outputs for bias, unsupported assumptions, omissions, and affected stakeholders.",
    20: "I know when AI-supported work requires human review, approval, or escalation.",
    21: "I can identify specific tasks where AI saves time or increases capacity.",
    22: "I can identify where AI improves quality, consistency, or decision speed.",
    23: "I measure at least one outcome, such as time, quality, revenue, cost, errors, or decision speed.",
    24: "I stop, redesign, or deprioritize AI uses that do not create meaningful value.",
    25: "I can explain, with evidence, how AI has improved professional or business performance.",
}
